sudo: false
language: python
env:
  - NODE_VERSION="16"
before_install:
  - nvm install $NODE_VERSION
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install tox-travis
before_script:
  - tox
script:
  - cd npm
  - npm ci
  - npm run copy:schemas
  - npm run semantic-release
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh ../scripts/automated-update-blockcerts.org.sh; fi' # if no changes (aka npm release), no commit then no PR
after_success:
  - pip install python-semantic-release
  - git config user.name botcerts
  - git config user.email botcerts@learningmachine.com
  - semantic-release publish --noop --verbosity=DEBUG
